name: Build and Deploy
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Check environment.yml
        run: find $GITHUB_WORKSPACE -name "environment.yml"

      - name: Setup Conda Environment 🏗️
        run: |
          conda env create -f $GITHUB_WORKSPACE/plato/environment.yml || conda env update --file $GITHUB_WORKSPACE/plato/environment.yml --prune
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate reveal_env

      - name: Build Documentation 📖
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate reveal_env
          cd docs
          make html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/html
          branch: gh-pages
