name: Build and Deploy
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Conda Environment 🏗️
        run: |
          conda env create -f environment.yml || conda env update --file environment.yml --prune
          source ~/.bashrc
          conda activate reveal_env

      - name: Install pygplates
        run: |
          source ~/.bashrc
          conda activate reveal_env
          pip install pygplates  # Install missing module

      - name: Verify Installation
        run: |
          source ~/.bashrc
          conda activate reveal_env
          python -c "import pygplates; print('pygplates installed successfully')"

      - name: Build Documentation 📖
        run: |
          source ~/.bashrc
          conda activate reveal_env
          cd docs
          make html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/html
          branch: gh-pages
